#
# Copyright (c) 2015, HUY PHAM., JSC
# All rights reserved.
#

source "https://github.com/CocoaPods/Specs.git"
use_frameworks!
platform :ios, "8.0"
project_name = "Pic Remember"
workspace "#{project_name}.xcworkspace"
xcodeproj "#{project_name}/#{project_name}.xcodeproj"

target project_name do
  pod 'KxMenu', '~> 1'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'DLRadioButton'
  pod 'M13Checkbox', '~> 1.1.0'
end
